### ISSUE TITLE
Can you change this to detail? :)

### ISSUE THREAD

**Issue by rudkjobing** [tokikanno/django-openapi#2]
https://github.com/tokikanno/django-openapi/blob/9ec204d2f16ed54eb02c936696ae81a9f2f97d6a/django_openapi/route.py#L55

**Comment by tokikanno** [comment]
sure :-P

may push to pip site later

https://github.com/tokikanno/django-openapi/commit/491562d50fee8025e9510063cde44f0c314a647e
