### ISSUE TITLE
Is it production ready?

### ISSUE THREAD

**Issue by zqabc** [tokikanno/django-openapi#4]
Can it be used in a production environment？

**Comment by tokikanno** [comment]
Yes and no.

I'm using it on my company's production-level API, the basic open API model auto-generation / validation function works pretty well to me. The re-written APIs were called every day by a massive of people and I got no error reports from them.

But 
1. As the readme said, there are still some to-do items.
2. I was just tried it on a small portion of our production APIs, there may be some other cases I haven't considered about.

**Comment by tokikanno** [comment]
this issue will be closed due to inactivity, free free to reopen for more discussion.
