### ISSUE TITLE
Any alternative tools? I found this repo is outdated

### ISSUE THREAD

**Issue by PaleNeutron** [tokikanno/django-openapi#5]
I'm also a fun of `FastApi` and I am looking for something just like this repo.

But this is for django2. Does it support Django4 or any other suggestions?

**Comment by tokikanno** [comment]
@PaleNeutron : You could try my another repo: https://github.com/tokikanno/django-mini-fastapi

I made this new tool after migrated all my company's project into Python3

It's a FastAPI adapter so it works more like FastAPI, I'm pretty sure it support at least Django3 (I don't have Django4 project, so just give it a try, if you encouter into any issue, you could report them in that repo)
